-- Generated by `prisma migrate diff` on 2026-07-30
-- IMPORTANT: Do NOT apply this automatically. This is for human review.
-- Apply with: psql $DATABASE_URL -f <this-file>
-- Or use `npx prisma db push` which will apply it non-destructively.

-- AlterTable
ALTER TABLE "AiUsage" ADD COLUMN     "estimatedCostUsd" DOUBLE PRECISION,
ADD COLUMN     "feature" TEXT,
ADD COLUMN     "provider" TEXT;
