-- Generated by `prisma migrate diff` on 2026-07-30
-- IMPORTANT: Do NOT apply this automatically. This is for human review.
-- Apply with: psql $DATABASE_URL -f <this-file>
-- Historical proposal only. Do not execute directly; replace with a reviewed,
-- isolated-clone-validated migration if this legacy shape is ever required.

-- AlterTable
ALTER TABLE "AiUsage" ADD COLUMN     "estimatedCostUsd" DOUBLE PRECISION,
ADD COLUMN     "feature" TEXT,
ADD COLUMN     "provider" TEXT;
